### ISSUE TITLE
Have any detailed readme information for integrate this packge to special server/client project?

### ISSUE THREAD

**Issue by gwenxia** [divio/django-simple-sso#23] opened 2017-09-29 15:46 UTC
Should server/client project must be  change lots of code for use sso packge,such as login/auth? Have any second develop documents?thx.

**Comment by FinalAngel** [comment] 2020-08-31 13:28
Duplicate of https://github.com/divio/django-simple-sso/issues/42

**Closed by FinalAngel** 2020-08-31 13:28 UTC
